#The frequency of the application
frequency: 100

#The size of images on the grid
imageSize: 30

#The size of the grid (must be a multiple of the imageSize)
gridSize: 920

#The time of a fear to disappears
fearTime: 4000

#The frequency of the fear (between fearTime of fearFrequency)
fearFrequency: 8000

#The speed of pigeons between pigeonSpeed & pigeonSpeed/2 (grids moved per frequency)
pigeonSpeed: 14

#The safe range for a pigeon to not be afraid
pigeonSecurityRange: 500

#The speed coefficient when a pigeon is running from a fear
highSpeed: 2

#The durability of food (number of frequency)
defaultDurability: 150